### ISSUE TITLE
Incorrect full screen aspect ratio

### ISSUE THREAD

**Issue by Hexaae** [ArjunNair/Zero-Emulator#23]
Even with option to keep aspect ratio in fullscreen... it appears incorrect here (Windows 10 x64 14393.576, 1080p 75Hz). Looks a little bit squashed vertically...

**Comment by ArjunNair** [comment]
What is your monitor's screen resolution?

**Comment by Hexaae** [comment]
1080p = 1920x1080 75Hz
In comparison http://zxmak2.codeplex.com/ uses correct aspect ratio in fullscreen.

**Comment by Hexaae** [comment]
I've just noticed there are some issues also in DirectX/GDI mode:
GDI: ignores "keep aspect ratio" settings in fullscreen, correct square pixels in window mode
DX: incorrect aspect ratio with non-square pixles when in window mode (see screenshots DX, GDI)
![image](https://cloud.githubusercontent.com/assets/8591462/21740789/79116a84-d4c4-11e6-9f29-81668a9ef325.png)

![image](https://cloud.githubusercontent.com/assets/8591462/21740781/3c069902-d4c4-11e6-9291-3ada21d5d62f.png)

**Comment by ArjunNair** [comment]
GDI is pixel perfect when it is in multiples of speccy resolution. If you do Alt +, it increases size by 50% of the speccy resolution, you will see the screen as in image 1 above. If you again Alt + it increases size by 50% more (so it now becomes +100% of original resolution), and since it's a multiple of the original, the pixel accuracy is maintained (as in image 2 above). In the case of GDI Full screen, no effort is maintained to ensure aspect ratio.

For DirectX, it prefers textures in powers of 2. Any other dimension of textures are scaled by the hardware. Since the speccy screen size is non-power of 2, the texture is always scaled, although enabling "Pixel Smoothing" fixes artifacts to a large extent (at the loss of some fidelity). Now, I *could* try to always use power of 2 textures but try to fit a "speccy window" to the texture, but this is probably not worth the headache. 

Thanks for pointing out the aspect ratio issue in DX full screen mode. Looks like it was a bug and I've made changes to the code to fix this.
