### ISSUE TITLE
Byte Count for Data Blocks in File Browser is Incorrect

### ISSUE THREAD

**Issue by wibblemonkey** [ArjunNair/Zero-Emulator#49]
The number of bytes displayed for a data block in the file browser is always two bytes more than the actual size of the data block. This can be recreated easily by loading a .tap or .tzx with a loading screen. The size will be displayed as 6914 bytes instead of 6912.

**Comment by ArjunNair** [comment]
Turns out that this is not a bug. The size being reported is coming from the PZX transformation process (all tape files are converted to PZX first). So even though the original file might have 6912 bytes, the actual bytes in that block after conversion might be more. And since Zero itself doesn't know a screen block differently from another data block, it reports the numbers it sees in the block data. Even Fuse reports the block size the same if you give it a PZX file. SpecEmu, which also supports PZX cleverly doesn't show the block size info. :)
